{{- if .Values.webapp.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "campusvibe.fullname" . }}
  labels:
    app: {{ include "campusvibe.name" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: campusvibe-web
  minReplicas: {{ .Values.webapp.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.webapp.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.webapp.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
